[package]
name = "saml"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
crypto = { workspace = true }
data-encoding = { workspace = true }
roxmltree = { workspace = true }
thiserror = { workspace = true }
