[kdcdefaults]
    kdc_ports = 8888
    kdc_tcp_ports = 8888

[libdefaults]
    default_realm = SAFFUI.TEST
    dns_lookup_kdc = false
    dns_lookup_realm = false
    rdns = false

[realms]
    SAFFUI.TEST = {
        kdc = localhost:8888
        admin_server = localhost
    }
