[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
commons = { workspace = true, features = ["http"] }
crypto = { workspace = true }
models = { workspace = true }
store = { workspace = true }

actix-web = { workspace = true }
deadpool-postgres = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
